# Generated by Django 2.1.7 on 2020-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_setupcamera_camera_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setcamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_id', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=250)),
                ('camera_num', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
