# Generated by Django 2.2 on 2020-01-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0003_setcamera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setupcamera',
        ),
    ]
